package com.trading.demo.portfolio.infrastructure.persistence.adapter;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import com.trading.demo.common.util.ReferenceIdGenerator;
import com.trading.demo.portfolio.domain.enums.PortfolioTransactionType;
import com.trading.demo.portfolio.domain.model.Portfolio;
import com.trading.demo.portfolio.infrastructure.persistence.entity.PortfolioEntity;
import com.trading.demo.portfolio.infrastructure.persistence.mapper.PortfolioMapper;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.trading.demo.portfolio.domain.port.PortfolioPort;
import com.trading.demo.portfolio.infrastructure.persistence.entity.PortfolioTransactionEntity;
import com.trading.demo.portfolio.infrastructure.persistence.repository.PortfolioJpaRepository;
import com.trading.demo.portfolio.infrastructure.persistence.repository.PortfolioTransactionJpaRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Repository
@Transactional
@RequiredArgsConstructor
@Slf4j
public class PortfolioAdapter implements PortfolioPort {
    private final PortfolioJpaRepository portfolioRepo;
    private final PortfolioTransactionJpaRepository transactionRepo;
    private final PortfolioMapper mapper;

    @Override
    @Transactional
    public void lockStock(UUID userId, UUID stockId, UUID orderId, int quantity) {
        // Chuyen co phieu tu kha dung sang phong toa
        int updated = portfolioRepo.lockStockForSale(userId, stockId, quantity);
        if (updated == 0) {
            throw new RuntimeException("Khong du co phieu kha dung de ban");
        }

        // Log transaction with idempotency using DB constraint
        // Reference ID will be generated by caller using ReferenceIdGenerator
        logPortfolioTransaction(userId, stockId, quantity,
                PortfolioTransactionType.LOCK_STOCK,
                ReferenceIdGenerator.generate(userId, stockId, orderId,
                        PortfolioTransactionType.LOCK_STOCK.name()
                ));
    }

    @Override
    @Transactional
    public void updateAfterTrade(UUID userId, UUID stockId, UUID orderId, int quantityChange, BigDecimal tradePrice) {
        if (quantityChange > 0) {
            // 1. Lay portfolio hien tai
            PortfolioEntity portfolio = portfolioRepo.findByUserIdAndStockId(userId, stockId)
                    .orElseGet(() -> mapper.toEntity(Portfolio.createEmpty(userId, stockId)));

            int oldQty = portfolio.getQuantity();
            BigDecimal oldAvg = portfolio.getAvgPrice();

            int newQty = oldQty + quantityChange;

            // 2. Tinh avg price moi
            BigDecimal newAvg = BigDecimal.ZERO;

            if (newQty > 0) {
                BigDecimal totalOld = oldAvg.multiply(BigDecimal.valueOf(oldQty));
                BigDecimal totalNew = tradePrice.multiply(BigDecimal.valueOf(quantityChange));

                newAvg = totalOld.add(totalNew)
                        .divide(BigDecimal.valueOf(newQty), 2, RoundingMode.HALF_UP);
            }

            // 3. Update DB
            portfolioRepo.updateAfterBuy(
                    userId,
                    stockId,
                    quantityChange,
                    newAvg
            );

            //4. Log transaction for buy trade
            logPortfolioTransaction(userId, stockId, quantityChange,
                    PortfolioTransactionType.TRADE_BUY,
                    ReferenceIdGenerator.generate(userId, stockId, orderId,
                            PortfolioTransactionType.TRADE_BUY.name()
                    ));
        } else if (quantityChange < 0) {
            int qty = Math.abs(quantityChange);

            // SELL
            // Khop lenh BAN: Tru ca tong va khoa (dung Math.abs de lay so duong)
            portfolioRepo.decreaseTotalAndLockedStock(userId, stockId, qty);

            // Log transaction for trade sell
            logPortfolioTransaction(userId, stockId, qty,
                    PortfolioTransactionType.TRADE_SELL,
                    ReferenceIdGenerator.generate(userId, stockId, orderId,
                            PortfolioTransactionType.TRADE_SELL.name()
                    ));
        }
    }

    @Override
    public Optional<Portfolio> findByUserIdAndStockId(UUID userId, UUID stockId) {
        return portfolioRepo.findByUserIdAndStockId(userId, stockId).map(mapper::toDomain);
    }

    @Override
    public Portfolio save(Portfolio portfolio) {
        return mapper.toDomain(portfolioRepo.save(mapper.toEntity(portfolio)));
    }

    @Override
    public List<Portfolio> findByUserId(UUID userId) {
        return portfolioRepo.findByUserId(userId)
                .stream()
                .map(mapper::toDomain)
                .toList();
    }

    @Override
    @Transactional
    public void releaseStock(UUID userId, UUID stockId, UUID orderId, int quantity) {
        // Huy lenh BAN: Giam so luong dang khoa
        portfolioRepo.unlockStock(userId, stockId, quantity);

        // Log transaction with idempotency using DB constraint
        // Reference ID will be generated by caller using ReferenceIdGenerator
        logPortfolioTransaction(userId, stockId, quantity,
                PortfolioTransactionType.RELEASE_STOCK,
                ReferenceIdGenerator.generate(userId, stockId, orderId,
                        PortfolioTransactionType.RELEASE_STOCK.name()
                ));
    }

    /**
     * Log portfolio transaction with idempotency using DB constraint
     *
     * @param userId          User ID
     * @param stockId         Stock ID
     * @param quantity        Quantity
     * @param transactionType Transaction type
     * @param referenceId     Reference ID for idempotency (null for auto-generated)
     */
    private void logPortfolioTransaction(UUID userId, UUID stockId, int quantity,
                                         PortfolioTransactionType transactionType,
                                         UUID referenceId) {
        try {
            PortfolioTransactionEntity transaction = PortfolioTransactionEntity.builder()
                    .userId(userId)
                    .stockId(stockId)
                    .quantity(quantity)
                    .transactionType(transactionType)
                    .referenceId(referenceId)
                    .build();

            transactionRepo.save(transaction);

        } catch (DuplicateKeyException e) {
            log.info("Portfolio transaction already processed (idempotent): {}", referenceId);
            // Transaction already processed - this is expected for retries
        }
    }
}
